sudo: required
services:
  - docker
    
before_install:
  - docker build -t eckseller/docker-react -f Dockerfile.dev .

script:
  - which node
  - node --version
  - nvm install 10.15.3
  - nvm use 10.15.3
  - node --version
  - which node
  - docker run eckseller/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-001950941586"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

  