sudo: required
services:
  - docker
    
before_install:
  - docker build -t eckseller/docker-react -f Dockerfile.dev .

script:
  - node --version
  - docker run eckseller/docker-react npm run test -- --coverage
