sudo: required
services:
  - docker
    
before_install:
  - docker build -t eckseller/docker-react -f Dockerfile.dev .

script:
  - which node
  - node --version
  - nvm install stable
  - nvm use stable
  - node --version
  - which node
  - docker run eckseller/docker-react npm run test -- --coverage
